import React, { createContext, useState, useContext } from 'react';

const translations = {
  de: {
    nav_park: "Park & Attraktionen",
    nav_tickets: "Auslastung & Tickets",
    nav_infos: "Infos",
    btn_book: "Tickets buchen",
    hero_title: "Willkommen im Aquarena Istanbul",
    hero_subtitle: "Erlebe den ultimativen Wasserspaß am Florya Güneş Strand. Von Adrenalin auf dem Jetski bis zur Entspannung auf dem SUP.",
    quick_book_title: "Tickets Sichern",
    btn_book_now: "Jetzt Buchen",
    capacity_title: "Aktuelle Auslastung",
    capacity_low: "Viel Platz!",
    capacity_med: "Gut besucht, jetzt buchen!",
    capacity_high: "Fast ausgebucht!",
    home_attractions_title: "Unsere Attraktionen am Strand",
    home_attractions_sub: "Entdecke die Vielfalt im Aquarena Istanbul – für jeden ist etwas dabei!",
    card_more: "Angebot ansehen",
    footer_desc: "Dein Premium Wasser-Freizeitpark. Action, Adrenalin und Erholung für die ganze Familie direkt am Meer.",
    footer_discover: "Entdecken",
    footer_info: "Informationen",
    footer_legal: "Rechtliches",
    opening_hours_label: "Öffnungszeiten:",
    opening_hours_time: "Mo - So: 10:00 - 18:00 Uhr",
    tickets_title: "Tickets Buchen & Auslastung",
    tickets_sub: "Sichere dir jetzt dein Erlebnis. Buche online und spare Wartezeit vor Ort!",
    step1: "1. Tickets auswählen",
    step2: "2. Dein Warenkorb",
    step3: "3. Datum & Zeit",
    step4: "4. Bezahlung (Demo)",
    step5: "Buchung erfolgreich!",
    btn_add_to_cart: "Hinzufügen",
    btn_go_to_cart: "Zum Warenkorb",
    btn_change: "Ändern",
    btn_checkout: "Weiter zur Kasse",
    btn_pay: "Jetzt kostenpflichtig buchen",
    cart_empty: "Dein Warenkorb ist noch leer.",
    remove: "Entfernen",
    total: "Gesamt",
    price_adult_child: "Erw. / Kind",
    from: "Ab",
    per_ticket: "pro Ticket",
    
    // Details
    detail_experience: "Das Erlebnis",
    detail_equipment: "Ausstattung",
    detail_safety: "Sicherheit & Regeln",
    btn_book_attraction: "Jetzt Tickets buchen",

    attr_1_title: "Wibit Action Park",
    attr_1_desc: "Ein riesiger, schwimmender Hindernisparcours im Meer. Klettern, rutschen und springen!",
    attr_1_exp: "Stürze dich in unser riesiges schwimmendes Abenteuer. Bezwinge den Ninja-Parcours, klettere auf den Action-Tower und rutsche die spektakuläre Freefall-Rutsche hinab ins erfrischende Wasser.",
    attr_1_equip: "Ausgestattet mit den neuesten Wibit Sports Aqua-Modulen. Die Elemente sind modular aufgebaut und bieten verschiedene Schwierigkeitsgrade für ultimativen Kletterspaß.",
    attr_1_safe: "Durchgehende Überwachung durch zertifizierte Rettungsschwimmer. Alle Teilnehmer müssen eine Schwimmweste tragen. Mindestalter: 8 Jahre (Freischwimmer-Abzeichen erforderlich).",

    attr_2_title: "High-Speed Jetski",
    attr_2_desc: "Adrenalin pur auf den Wellen. Miete dir einen unserer modernen Jetskis und gib Gas.",
    attr_2_exp: "Spüre die Kraft und Geschwindigkeit auf dem offenen Meer! Gleite über die Wellen und erlebe einen unvergleichlichen Adrenalinkick vor der atemberaubenden Kulisse Istanbuls.",
    attr_2_equip: "Wir nutzen die neuesten Yamaha WaveRunner EX Sport (100 PS) – extrem wendig, sicher in den Kurven und umweltfreundlicher dank modernster Motorentechnik.",
    attr_2_safe: "Ausgestattet mit GPS-Tracking und automatischer Notabschaltung (Kill Switch). Vor Fahrtantritt gibt es eine ausführliche Sicherheitseinweisung. Mindestalter Fahrer: 16 Jahre (Führerscheinfrei in markierter Bucht).",

    attr_3_title: "Stand-Up-Paddling",
    attr_3_desc: "Erkunde das Meer entspannt auf dem SUP. Perfekt für das Training oder den Sonnenuntergang.",
    attr_3_exp: "Genieße die Ruhe auf dem Wasser. Egal ob als Ganzkörper-Workout am Morgen oder entspannt in den Sonnenuntergang – SUP ist die perfekte Aktivität für Jung und Alt.",
    attr_3_equip: "Hochwertige, extrem stabile aufblasbare SUP-Boards von Fanatic & Red Paddle. Wir bieten verschiedene Board-Längen für Anfänger und Fortgeschrittene an.",
    attr_3_safe: "Alle Boards sind mit einer Leash (Sicherheitsleine am Fußgelenk) ausgestattet. Auf Wunsch stellen wir Schwimmwesten zur Verfügung. Kurze Paddel-Einweisung am Strand inklusive.",

    attr_4_title: "Tretboot Verleih",
    attr_4_desc: "Spaß für die ganze Familie oder romantisch zu zweit. Gemütlich über die Wellen gleiten.",
    attr_4_exp: "Der absolute Klassiker für die ganze Familie oder ein romantisches Date. Gleite gemütlich über die sanften Wellen und entdecke die Küste in deinem eigenen Tempo.",
    attr_4_equip: "Unsere modernen 4-Sitzer Tretboote bieten ergonomische Sitze und ein Sonnendach. Einige Modelle sind sogar mit einer kleinen Wasserrutsche am Heck ausgestattet!",
    attr_4_safe: "Die Boote verfügen über ein unsinkbares Design-Konzept. Für Kinder unter 12 Jahren gilt eine Schwimmwesten-Pflicht an Bord.",

    cat_adult: "Erwachsener",
    cat_child: "Kind (unter 12)",
    cat_student: "Student",
    cat_disabled: "Behinderte",
    cat_senior: "Senior (65+)",
    dur_10min: "10 Min.",
    dur_30min: "30 Min.",
    dur_1h: "1 Std.",
    dur_2h: "2 Std.",
    dur_halfday: "Halbtag (4 Std.)",
    dur_fullday: "Tageskarte",
    btn_configure: "Konfigurieren",
    select_duration: "Dauer wählen:",
    persons: "Personen:",
    total_calc: "Berechneter Preis:",
    close: "Schließen",

    // New Presentation Features
    weather_water: "Wasser",
    weather_air: "Luft",
    testimonials_title: "Das sagen unsere Gäste",
    testi_1_text: "Ein unglaubliches Erlebnis! Der Jetski-Verleih war super professionell.",
    testi_1_author: "Markus T.",
    testi_2_text: "Der Wibit Park ist riesig! Wir hatten als Familie unglaublich viel Spaß.",
    testi_2_author: "Sarah L.",
    testi_3_text: "Sehr entspanntes SUP in den Sonnenuntergang. Wunderschöne Kulisse!",
    testi_3_author: "Aylin K.",
    map_title: "Interaktiver Parkplan",
    map_desc: "Hier findest du eine Übersicht über alle Aktivitäten am Florya Strand.",
    nav_map: "Parkplan",
    nav_faq: "FAQ",
    faq_title: "Häufig gestellte Fragen (FAQ)",
    faq_desc: "Hier findest du Antworten auf die wichtigsten Fragen rund um deinen Besuch.",
    faq_1_q: "Muss ich gut schwimmen können?",
    faq_1_a: "Ja, für alle Aktivitäten im Wasser (Wibit, Jetski) ist ein sicheres Schwimmen zwingende Voraussetzung. Schwimmwesten werden selbstverständlich von uns für alle Attraktionen kostenfrei gestellt.",
    faq_2_q: "Gibt es Schließfächer für Wertsachen?",
    faq_2_a: "Ja, direkt am Haupteingang und bei den Duschen befinden sich überwachte Schließfächer, die gegen eine geringe Gebühr genutzt werden können.",
    faq_3_q: "Was passiert bei schlechtem Wetter?",
    faq_3_a: "Bei starkem Wind, Gewitter oder Sturm müssen wir den Betrieb aus Sicherheitsgründen sofort einstellen. Vorab gebuchte Tickets behalten in diesem Fall ihre Gültigkeit für einen beliebigen Ersatztermin.",
    faq_4_q: "Darf ich eigenes Essen und Getränke mitbringen?",
    faq_4_a: "Ja, kleine Snacks und Getränke in Plastikflaschen sind erlaubt. Aus Sicherheitsgründen sind Glasflaschen am gesamten Strand jedoch streng verboten.",
    nav_events: "Events",
    events_title: "Beach & Water Events",
    events_sub: "Mach mit bei unseren actionreichen Turnieren und Community-Events!",
    ev_1_title: "Wasser-Volleyball Turnier",
    ev_1_date: "Jeden 1. Samstag im Monat",
    ev_1_desc: "Unser Highlight im flachen Wasser! Tritt mit deinem Team im Wasser-Volleyball an. Tolle Preise, viel Musik und jede Menge Spaß für Spieler und Zuschauer.",
    ev_2_title: "Wasserball (Water Polo)",
    ev_2_date: "Jeden 2. Sonntag im Monat",
    ev_2_desc: "Für die Sportlichen: Wasserball-Turniere in unserer abgegrenzten Meeres-Arena. Beweise Ausdauer und Teamgeist auf dem offenen Wasser.",
    ev_3_title: "Capture the Flag auf dem Wibit",
    ev_3_date: "Jeden 3. Samstag im Monat",
    ev_3_desc: "Action pur! Zwei Teams treten auf dem riesigen Wibit Hindernisparcours gegeneinander an. Taktik, Schnelligkeit und Balance sind gefragt, um die Flagge zu erobern.",
    btn_join_event: "Jetzt anmelden",
    btn_learn_more: "Mehr erfahren",
    nav_contest: "Gewinnspiel",
    contest_title: "Großes Eröffnungs-Gewinnspiel",
    contest_subtitle: "Gewinne eine Reise zum Europa-Park in Rust!",
    contest_desc: "Die Person, die in den ersten drei Monaten nach Eröffnung unseres Parks ein Instagram-Reel oder TikTok mit den meisten Views/Likes macht, gewinnt eine Reise zum Europa-Park in Rust inkl. Hotel und Anreise!",
    contest_rules_title: "So machst du mit:",
    contest_rule_1: "Besuche den Aquarena Istanbul und mache ein cooles Video.",
    contest_rule_2: "Poste es als Reel auf Instagram oder auf TikTok.",
    contest_rule_3: "Markiere unseren offiziellen Account in deinem Post.",
    contest_rule_4: "Sammle so viele Views und Likes wie möglich!"
  },
  en: {
    nav_park: "Park & Attractions",
    nav_tickets: "Capacity & Tickets",
    nav_infos: "Info",
    btn_book: "Book Tickets",
    hero_title: "Welcome to Aquarena Istanbul",
    hero_subtitle: "Experience the ultimate water fun at Florya Güneş Beach. From jet ski adrenaline to SUP relaxation.",
    quick_book_title: "Get Tickets",
    btn_book_now: "Book Now",
    capacity_title: "Current Capacity",
    capacity_low: "Plenty of space!",
    capacity_med: "Busy, book now!",
    capacity_high: "Almost fully booked!",
    home_attractions_title: "Our Beach Attractions",
    home_attractions_sub: "Discover the variety at Aquarena Istanbul – there's something for everyone!",
    card_more: "View Offer",
    footer_desc: "Your premium water amusement park. Action, adrenaline, and relaxation for the whole family right by the sea.",
    footer_discover: "Discover",
    footer_info: "Information",
    footer_legal: "Legal",
    opening_hours_label: "Opening Hours:",
    opening_hours_time: "Mon - Sun: 10:00 AM - 6:00 PM",
    tickets_title: "Book Tickets & Capacity",
    tickets_sub: "Secure your experience now. Book online and save time waiting on site!",
    step1: "1. Select Tickets",
    step2: "2. Your Cart",
    step3: "3. Date & Time",
    step4: "4. Payment (Demo)",
    step5: "Booking Successful!",
    btn_add_to_cart: "Add to Cart",
    btn_go_to_cart: "Go to Cart",
    btn_change: "Change",
    btn_checkout: "Proceed to Checkout",
    btn_pay: "Pay Now",
    cart_empty: "Your cart is empty.",
    remove: "Remove",
    total: "Total",
    price_adult_child: "Adult / Child",
    from: "From",
    per_ticket: "per Ticket",

    detail_experience: "The Experience",
    detail_equipment: "Equipment",
    detail_safety: "Safety & Rules",
    btn_book_attraction: "Book Tickets Now",

    attr_1_title: "Wibit Action Park",
    attr_1_desc: "A massive, floating obstacle course in the sea. Climb, slide, and jump!",
    attr_1_exp: "Dive into our huge floating adventure. Conquer the Ninja course, climb the Action Tower, and slide down the spectacular Freefall slide into the refreshing water.",
    attr_1_equip: "Equipped with the latest Wibit Sports Aqua Modules. The elements are modular and offer various difficulty levels for ultimate climbing fun.",
    attr_1_safe: "Continuous monitoring by certified lifeguards. All participants must wear a life jacket. Minimum age: 8 years (swimming certificate required).",

    attr_2_title: "High-Speed Jet Ski",
    attr_2_desc: "Pure adrenaline on the waves. Rent one of our modern jet skis and hit the gas.",
    attr_2_exp: "Feel the power and speed on the open sea! Glide over the waves and experience an unparalleled adrenaline rush against the breathtaking backdrop of Istanbul.",
    attr_2_equip: "We use the latest Yamaha WaveRunner EX Sport (100 HP) – extremely agile, safe in corners, and environmentally friendly thanks to modern engine technology.",
    attr_2_safe: "Equipped with GPS tracking and automatic emergency shutdown (Kill Switch). A detailed safety briefing is provided before departure. Minimum driver age: 16 years (no license required in the marked bay).",

    attr_3_title: "Stand-Up Paddling",
    attr_3_desc: "Explore the sea relaxed on a SUP. Perfect for a workout or a sunset.",
    attr_3_exp: "Enjoy the tranquility on the water. Whether as a full-body workout in the morning or a relaxed ride into the sunset – SUP is the perfect activity for young and old.",
    attr_3_equip: "High-quality, extremely stable inflatable SUP boards from Fanatic & Red Paddle. We offer various board lengths for beginners and advanced paddlers.",
    attr_3_safe: "All boards are equipped with a leash (safety line on the ankle). Life jackets are available on request. Short paddling instruction at the beach included.",

    attr_4_title: "Pedal Boat Rental",
    attr_4_desc: "Fun for the whole family or romantic for two. Glide comfortably over the waves.",
    attr_4_exp: "The absolute classic for the whole family or a romantic date. Glide comfortably over the gentle waves and discover the coast at your own pace.",
    attr_4_equip: "Our modern 4-seater pedal boats offer ergonomic seats and a sun canopy. Some models are even equipped with a small water slide at the stern!",
    attr_4_safe: "The boats feature an unsinkable design concept. Life jackets are mandatory on board for children under 12 years.",

    cat_adult: "Adult",
    cat_child: "Child (under 12)",
    cat_student: "Student",
    cat_disabled: "Disabled Person",
    cat_senior: "Senior (65+)",
    dur_10min: "10 Min.",
    dur_30min: "30 Min.",
    dur_1h: "1 Hour",
    dur_2h: "2 Hours",
    dur_halfday: "Half Day (4h)",
    dur_fullday: "Full Day",
    btn_configure: "Configure",
    select_duration: "Select Duration:",
    persons: "Persons:",
    total_calc: "Calculated Price:",
    close: "Close",

    weather_water: "Water",
    weather_air: "Air",
    testimonials_title: "What our guests say",
    testi_1_text: "An incredible experience! The jet ski rental was super professional.",
    testi_1_author: "Markus T.",
    testi_2_text: "The Wibit Park is huge! We had so much fun as a family.",
    testi_2_author: "Sarah L.",
    testi_3_text: "Very relaxed SUP into the sunset. Beautiful scenery!",
    testi_3_author: "Aylin K.",
    map_title: "Interactive Park Map",
    map_desc: "Here you can find an overview of all activities at Florya Beach.",
    nav_map: "Park Map",
    nav_faq: "FAQ",
    faq_title: "Frequently Asked Questions (FAQ)",
    faq_desc: "Find answers to the most important questions about your visit.",
    faq_1_q: "Do I need to be a good swimmer?",
    faq_1_a: "Yes, confident swimming is a mandatory requirement for all water activities. Life jackets are provided free of charge for all attractions.",
    faq_2_q: "Are there lockers for valuables?",
    faq_2_a: "Yes, monitored lockers are available right at the main entrance and near the showers for a small fee.",
    faq_3_q: "What happens in bad weather?",
    faq_3_a: "In case of strong winds or thunderstorms, we must suspend operations for safety reasons. Pre-booked tickets remain valid for any alternative date.",
    faq_4_q: "Can I bring my own food and drinks?",
    faq_4_a: "Yes, small snacks and drinks in plastic bottles are allowed. However, glass bottles are strictly prohibited on the entire beach for safety reasons.",
    nav_events: "Events",
    events_title: "Beach & Water Events",
    events_sub: "Join our action-packed tournaments and community events!",
    ev_1_title: "Water Volleyball Tournament",
    ev_1_date: "Every 1st Saturday of the month",
    ev_1_desc: "Our highlight in the shallow water! Compete with your team in water volleyball. Great prizes, lots of music and tons of fun for players and spectators.",
    ev_2_title: "Water Polo",
    ev_2_date: "Every 2nd Sunday of the month",
    ev_2_desc: "For the sporty ones: Water polo tournaments in our marked sea arena. Prove endurance and team spirit on the open water.",
    ev_3_title: "Capture the Flag on Wibit",
    ev_3_date: "Every 3rd Saturday of the month",
    ev_3_desc: "Pure action! Two teams compete on the massive Wibit obstacle course. Tactics, speed, and balance are required to capture the flag.",
    btn_join_event: "Register Now",
    btn_learn_more: "Learn more",
    nav_contest: "Contest",
    contest_title: "Grand Opening Contest",
    contest_subtitle: "Win a trip to Europa-Park in Rust!",
    contest_desc: "The person who makes an Instagram Reel or TikTok with the most views/likes in the first three months after the opening of our park wins a trip to Europa-Park in Rust incl. hotel and travel!",
    contest_rules_title: "How to enter:",
    contest_rule_1: "Visit Aquarena Istanbul and make a cool video.",
    contest_rule_2: "Post it as a Reel on Instagram or on TikTok.",
    contest_rule_3: "Tag our official account in your post.",
    contest_rule_4: "Collect as many views and likes as possible!"
  },
  tr: {
    nav_park: "Park & Eğlence",
    nav_tickets: "Doluluk & Biletler",
    nav_infos: "Bilgi",
    btn_book: "Bilet Al",
    hero_title: "Aquarena Istanbul'a Hoş Geldiniz",
    hero_subtitle: "Florya Güneş Plajı'nda nihai su eğlencesini yaşayın. Jet ski adrenalinden SUP rahatlamasına kadar.",
    quick_book_title: "Biletlerini Al",
    btn_book_now: "Şimdi Rezervasyon Yap",
    capacity_title: "Mevcut Doluluk",
    capacity_low: "Bolca yer var!",
    capacity_med: "Yoğun, şimdi ayırtın!",
    capacity_high: "Neredeyse dolu!",
    home_attractions_title: "Plaj Aktivitelerimiz",
    home_attractions_sub: "Aquarena Istanbul'daki çeşitliliği keşfedin - herkes için bir şey var!",
    card_more: "Teklifi İncele",
    footer_desc: "Premium su eğlence parkınız. Deniz kenarında tüm aile için aksiyon, adrenalin ve rahatlama.",
    footer_discover: "Keşfet",
    footer_info: "Bilgi",
    footer_legal: "Yasal",
    opening_hours_label: "Çalışma Saatleri:",
    opening_hours_time: "Pzt - Paz: 10:00 - 18:00",
    tickets_title: "Bilet Al & Doluluk",
    tickets_sub: "Deneyiminizi şimdi güvence altına alın. Çevrimiçi rezervasyon yapın ve sırada beklemeyin!",
    step1: "1. Biletleri Seçin",
    step2: "2. Sepetiniz",
    step3: "3. Tarih & Saat",
    step4: "4. Ödeme (Demo)",
    step5: "Rezervasyon Başarılı!",
    btn_add_to_cart: "Ekle",
    btn_go_to_cart: "Sepete Git",
    btn_change: "Değiştir",
    btn_checkout: "Ödemeye Geç",
    btn_pay: "Şimdi Öde",
    cart_empty: "Sepetiniz boş.",
    remove: "Kaldır",
    total: "Toplam",
    price_adult_child: "Yetişkin / Çocuk",
    from: "İtibaren",
    per_ticket: "Bilet başına",

    detail_experience: "Deneyim",
    detail_equipment: "Ekipman",
    detail_safety: "Güvenlik ve Kurallar",
    btn_book_attraction: "Şimdi Bilet Al",

    attr_1_title: "Wibit Aksiyon Parkı",
    attr_1_desc: "Denizde devasa, yüzen bir engel parkuru. Tırman, kay ve atla!",
    attr_1_exp: "Devasa yüzen maceramıza dalın. Ninja parkurunu fethedin, Aksiyon Kulesi'ne tırmanın ve serin sulara inen muhteşem Freefall kaydırağından aşağı kayın.",
    attr_1_equip: "En yeni Wibit Sports Aqua Modülleri ile donatılmıştır. Elemanlar modülerdir ve nihai tırmanma eğlencesi için çeşitli zorluk seviyeleri sunar.",
    attr_1_safe: "Sertifikalı cankurtaranlar tarafından sürekli izleme. Tüm katılımcılar can yeleği giymelidir. Minimum yaş: 8 (yüzme sertifikası gereklidir).",

    attr_2_title: "Yüksek Hızlı Jet Ski",
    attr_2_desc: "Dalgalarda saf adrenalin. Modern jet skilerimizden birini kirala ve gaza bas.",
    attr_2_exp: "Açık denizde gücü ve hızı hissedin! Dalgaların üzerinde süzülün ve İstanbul'un nefes kesen manzarasına karşı benzersiz bir adrenalin patlaması yaşayın.",
    attr_2_equip: "En yeni Yamaha WaveRunner EX Sport (100 HP) kullanıyoruz - modern motor teknolojisi sayesinde son derece çevik, virajlarda güvenli ve çevre dostu.",
    attr_2_safe: "GPS takibi ve otomatik acil durum kapatma (Kill Switch) ile donatılmıştır. Kalkıştan önce detaylı bir güvenlik brifingi verilir. Minimum sürücü yaşı: 16 (işaretli koyda ehliyet gerekmez).",

    attr_3_title: "Ayakta Kürek (SUP)",
    attr_3_desc: "SUP ile denizi rahatça keşfet. Antrenman veya gün batımı için mükemmel.",
    attr_3_exp: "Suyun üzerindeki huzurun tadını çıkarın. İster sabahları tam vücut antrenmanı olarak, ister gün batımında rahat bir sürüş olarak – SUP genç ve yaşlı herkes için mükemmel bir aktivitedir.",
    attr_3_equip: "Fanatic ve Red Paddle'dan yüksek kaliteli, son derece sağlam şişme SUP tahtaları. Yeni başlayanlar ve ileri düzey kürekçiler için çeşitli tahta uzunlukları sunuyoruz.",
    attr_3_safe: "Tüm tahtalar bir tasma (ayak bileğinde güvenlik halatı) ile donatılmıştır. İstek üzerine can yelekleri mevcuttur. Plajda kısa kürek çekme eğitimi dahildir.",

    attr_4_title: "Deniz Bisikleti Kiralama",
    attr_4_desc: "Tüm aile için eğlence veya iki kişi için romantik. Dalgaların üzerinde rahatça süzülün.",
    attr_4_exp: "Tüm aile için mutlak bir klasik veya romantik bir buluşma. Hafif dalgaların üzerinde rahatça süzülün ve sahili kendi hızınızda keşfedin.",
    attr_4_equip: "Modern 4 kişilik deniz bisikletlerimiz ergonomik koltuklar ve bir güneşlik sunar. Bazı modeller arka tarafta küçük bir su kaydırağı ile donatılmıştır!",
    attr_4_safe: "Tekneler batmaz bir tasarım konseptine sahiptir. 12 yaşından küçük çocuklar için teknede can yeleği takmak zorunludur.",

    cat_adult: "Yetişkin",
    cat_child: "Çocuk (12 yaş altı)",
    cat_student: "Öğrenci",
    cat_disabled: "Engelli Birey",
    cat_senior: "Yaşlı (65+)",
    dur_10min: "10 Dk.",
    dur_30min: "30 Dk.",
    dur_1h: "1 Saat",
    dur_2h: "2 Saat",
    dur_halfday: "Yarım Gün (4 Saat)",
    dur_fullday: "Tam Gün",
    btn_configure: "Yapılandır",
    select_duration: "Süre Seçin:",
    persons: "Kişiler:",
    total_calc: "Hesaplanan Fiyat:",
    close: "Kapat",

    weather_water: "Su",
    weather_air: "Hava",
    testimonials_title: "Misafirlerimiz ne diyor",
    testi_1_text: "İnanılmaz bir deneyim! Jet ski kiralama süper profesyoneldi.",
    testi_1_author: "Markus T.",
    testi_2_text: "Wibit Park devasa! Ailece çok eğlendik.",
    testi_2_author: "Sarah L.",
    testi_3_text: "Gün batımına doğru çok rahatlatıcı bir SUP. Harika manzara!",
    testi_3_author: "Aylin K.",
    map_title: "İnteraktif Park Planı",
    map_desc: "Florya Plajı'ndaki tüm etkinliklere genel bir bakış bulabilirsiniz.",
    nav_map: "Park Planı",
    nav_faq: "SSS",
    faq_title: "Sıkça Sorulan Sorular (SSS)",
    faq_desc: "Ziyaretinizle ilgili en önemli soruların yanıtlarını burada bulabilirsiniz.",
    faq_1_q: "İyi yüzme bilmem gerekiyor mu?",
    faq_1_a: "Evet, sudaki tüm aktiviteler (Wibit, jet ski) için güvenli yüzme zorunludur. Tüm eğlenceler için can yelekleri tarafımızdan ücretsiz olarak sağlanmaktadır.",
    faq_2_q: "Değerli eşyalar için kilitli dolap var mı?",
    faq_2_a: "Evet, ana girişte ve duşların yanında cüzi bir ücret karşılığında kullanabileceğiniz izlenen kilitli dolaplar bulunmaktadır.",
    faq_3_q: "Kötü hava koşullarında ne olur?",
    faq_3_a: "Kuvvetli rüzgar, fırtına veya şimşek durumunda güvenlik nedeniyle operasyonları durdurmak zorundayız. Önceden alınan biletler herhangi bir alternatif tarih için geçerli kalır.",
    faq_4_q: "Kendi yiyecek ve içeceklerimi getirebilir miyim?",
    faq_4_a: "Evet, küçük atıştırmalıklar ve plastik şişelerdeki içecekler serbesttir. Ancak güvenlik nedeniyle tüm plajda cam şişeler kesinlikle yasaktır.",
    nav_events: "Etkinlikler",
    events_title: "Plaj ve Su Etkinlikleri",
    events_sub: "Aksiyon dolu turnuvalarımıza ve topluluk etkinliklerimize katılın!",
    ev_1_title: "Su Voleybolu Turnuvası",
    ev_1_date: "Her ayın 1. Cumartesi günü",
    ev_1_desc: "Sığ sulardaki en büyük etkinliğimiz! Takımınızla su voleybolunda yarışın. Harika ödüller, bol müzik ve oyuncular ve izleyiciler için tonlarca eğlence.",
    ev_2_title: "Su Topu (Water Polo)",
    ev_2_date: "Her ayın 2. Pazar günü",
    ev_2_desc: "Sportmenler için: İşaretli deniz arenamızda su topu turnuvaları. Açık suda dayanıklılığınızı ve takım ruhunuzu kanıtlayın.",
    ev_3_title: "Wibit'te Bayrağı Yakala",
    ev_3_date: "Her ayın 3. Cumartesi günü",
    ev_3_desc: "Saf aksiyon! İki takım devasa Wibit engel parkurunda yarışıyor. Bayrağı yakalamak için taktik, hız ve denge gerekiyor.",
    btn_join_event: "Şimdi Kaydol",
    btn_learn_more: "Daha fazla bilgi",
    nav_contest: "Yarışma",
    contest_title: "Büyük Açılış Yarışması",
    contest_subtitle: "Rust'taki Europa-Park'a seyahat kazan!",
    contest_desc: "Parkımızın açılışından sonraki ilk üç ay içinde en çok izlenme/beğeni alan bir Instagram Reel veya TikTok yapan kişi, Rust'taki Europa-Park'a otel ve seyahat dahil bir gezi kazanıyor!",
    contest_rules_title: "Nasıl katılınır:",
    contest_rule_1: "Europa-Park İstanbul'u ziyaret et ve harika bir video çek.",
    contest_rule_2: "Bunu Instagram'da bir Reel veya TikTok'ta paylaş.",
    contest_rule_3: "Gönderinde resmi hesabımızı etiketle.",
    contest_rule_4: "Mümkün olduğunca çok izlenme ve beğeni topla!"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('de');

  const t = (key) => {
    return translations[language][key] || key;
  };

  const formatPrice = (priceEur) => {
    if (language === 'tr') {
      const priceTry = priceEur * 35.23;
      return new Intl.NumberFormat('tr-TR', { style: 'currency', currency: 'TRY' }).format(priceTry);
    }
    return new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(priceEur);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatPrice }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
